openapi: 3.0.3
info:
  title: Swagger Livraria - OpenAPI 3.0
  description: |
    Esse é um teste de uma livraria.
  version: 1.0.0
tags:
  - name: books

paths:
  /livros:
    get:
      tags:
        - books
      summary: Buscar livro
      description: Buscar livro dentro da biblioteca
      responses:
        '200':
          description: Busca feita com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    titulo:
                      type: string
                      example: Captive Prince
                    autor:
                      type: string
                      example: C.S. Pacat
                    ano:
                      type: integer
                      example: 2015
        '400':
          description: ID inválido fornecido
        '404':
          description: Livro não encontrado

    post:
      tags:
        - books
      summary: Adicionar um novo livro
      requestBody:
        description: Adicionar um novo livro
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                titulo:
                  type: string
                  example: Príncipe Cativo
                autor:
                  type: string
                  example: C.S. Pacat
                ano:
                  type: integer
                  example: 2015
      responses:
        '201':
          description: Livro criado com sucesso
        '400':
          description: Requisição inválida
          
/livros/{id}











































